disabled_rules: # rule identifiers to exclude from running
- trailing_whitespace
- type_name
- nesting
- line_length
- function_body_length
- identifier_name
- weak_delegate
- empty_enum_arguments
- unused_closure_parameter
- multiple_closures_with_trailing_closure
- large_tuple
- switch_case_alignment
- function_parameter_count

excluded: # paths to ignore during linting. Takes precedence over `included`.
- Pods
