os: osx
osx_image: xcode10.1

cache:
directories:
# General SwiftPM
# Danger Swift plugins, like Yams
- .build
- ~/.danger-swift

install:
- npm install git+https://github.com/DefinitelyTyped/tsd -g
# Grab the latest Danger JS from npm
- npm install -g danger
# Compile the Danger runtime
- swift build

script:
# Run the Dangerfile.swift
- swift run danger-swift ci
# Test my app...
- [your other commands]
