os: osx
osx_image: xcode10.1

cache:
directories:
# General SwiftPM
# Danger Swift plugins, like Yams
- .build
- ~/.danger-swift

install:
# Grab the latest Danger JS from npm
- npm install -g danger
#- gem install danger-slack
# - brew install swiftlint # This is for the Danger SwiftLint plugin. If not installed yet
# Compile the Danger runtime
- swift build

script:
# Run the Dangerfile.swift
- swift run danger-swift ci
# Test my app...
