os: osx
osx_image: xcode10.1

cache:
directories:
# General SwiftPM
# Danger Swift plugins, like Yams
- .build
- ~/.danger-swift

install:
# Grab the latest Danger JS from npm
- npm install -g danger
# - brew install swiftlint # This is for the Danger SwiftLint plugin. If not installed yet
# Compile the Danger runtime
- swift build

deploy:
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master

script:
# Run the Dangerfile.swift
- swift run danger-swift ci
# Test my app...
